[project]
name = "xvisor"
version = "0.1.0"
description = ""
authors = [
    {name = "XL1TTE",email = "xl1tte.dev@gmail.com"}
]
license = "MIT"
requires-python = ">=3.9,<3.13"

[tool.poetry]
packages = [{ include = "*", from = "src" }]

[[tool.poetry.source]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[tool.poetry.dependencies]
torch = { version = ">=2.0.0", source = "pytorch-cu121" }
torchvision = { version = ">=0.15.0", source = "pytorch-cu121" }

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api" 
